name: issue-project-test

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  to-project:
    if: github.actor == secrets.CUSTOMER
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Test Project
          column: Backlog
          action: add
          repo-token: ${{ secrets.GITHUB_TOKEN }}
