name: issue-project-test

on:
  issues:
    types:
      - opened
      - reopened

env:
  CUSTOMER: ${{ secrets.CUSTOMER }}

jobs:
  to-project:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor == env.CUSTOMER
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Test Project
          column: Backlog
          action: add
          repo-token: ${{ secrets.GITHUB_TOKEN }}
